language: python
sudo: false
python:
- 3.4
- 3.5
- 3.6
- 3.7-dev
install:
- pip install -U pip
- pip install tox coveralls
script:
- tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/' | sed
  -e 's/-dev//')
after_success:
- coveralls --verbose
notifications:
  email: false
jobs:
  include:
  - stage: deploy
    deploy:
      provider: pypi
      user: c.tippett
      password:
        secure: Pe/GTk8fOWkSMzemBsXmc4KSo3PWCA8XBHphWx+vebVcz4GIpm0PrNmYjXKX+En4/3xvuuLfgcV+g5Jy2O/nKRI7oQ9YSO1XwUu2N1mSbtCTRCRbjHyZkrFfb8gJOijpoaPmyTzXSE6Kt9Os5jv/5Fasm2L8GuLuD7R6ywZNGp3ZsRVdkyTi/GBpSR0kT2qOWFOW/XihxaZ/HGmiPWEHKEMoJ0i6dw/DIHXDA+3NfD6bXgi4pNKK1qWCcX68egO/V4P4+acqR9OtHbY5zK2vfAIsxqCcAcv4MkW1+unt3zCe3RjQTfyB1Zbe9CBejVU+kp5+CNXzrDMIs7dJk9p1ZPN/PLipJ00CWH73DOt33nxSVEHDucybPOAxouALYHW5Yd1Iwqf6/Iymv08eBV6oHfbUGVbZJXGvFJ1CoaWPL3kX7fRHISmL/ITzqxeQdONB4VqiS5TKF3UlSDz6ir5KFcjpjf4BpgHf5RVSTgzHtLnBnryGWM/pjhoE3Km2R4M+eTjbTcBjTCvKv+btB5aE/QLaTiFMj0N2tW3ik91KxbKXh8Ui5Vn0UkakIX3+mI50fg/zFOUITjAPU3L8CvouwxVfidwxasPD1D62UyGBS0vlqP0Blia7kGLebg5xl2OuzPPAlTAoi5INb3ZHeTswxvXgwrFDBToMuf7KxSnOSxg=
      distributions: sdist bdist_wheel
      on:
        tags: true
        branch: master
        repo: christippett/hangouts-helper
